// Generated by gencpp from file mult_driver/convert_to_quaternionRequest.msg
// DO NOT EDIT!


#ifndef MULT_DRIVER_MESSAGE_CONVERT_TO_QUATERNIONREQUEST_H
#define MULT_DRIVER_MESSAGE_CONVERT_TO_QUATERNIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace mult_driver
{
template <class ContainerAllocator>
struct convert_to_quaternionRequest_
{
  typedef convert_to_quaternionRequest_<ContainerAllocator> Type;

  convert_to_quaternionRequest_()
    : euler_angles()  {
    }
  convert_to_quaternionRequest_(const ContainerAllocator& _alloc)
    : euler_angles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _euler_angles_type;
  _euler_angles_type euler_angles;





  typedef boost::shared_ptr< ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct convert_to_quaternionRequest_

typedef ::mult_driver::convert_to_quaternionRequest_<std::allocator<void> > convert_to_quaternionRequest;

typedef boost::shared_ptr< ::mult_driver::convert_to_quaternionRequest > convert_to_quaternionRequestPtr;
typedef boost::shared_ptr< ::mult_driver::convert_to_quaternionRequest const> convert_to_quaternionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator1> & lhs, const ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.euler_angles == rhs.euler_angles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator1> & lhs, const ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mult_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01954336000a228e12c0ea86ec76073a";
  }

  static const char* value(const ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01954336000a228eULL;
  static const uint64_t static_value2 = 0x12c0ea86ec76073aULL;
};

template<class ContainerAllocator>
struct DataType< ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mult_driver/convert_to_quaternionRequest";
  }

  static const char* value(const ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 euler_angles\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.euler_angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct convert_to_quaternionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mult_driver::convert_to_quaternionRequest_<ContainerAllocator>& v)
  {
    s << indent << "euler_angles: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.euler_angles);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULT_DRIVER_MESSAGE_CONVERT_TO_QUATERNIONREQUEST_H
