// Generated by gencpp from file imu_driver/EulerToQuaternionRequest.msg
// DO NOT EDIT!


#ifndef IMU_DRIVER_MESSAGE_EULERTOQUATERNIONREQUEST_H
#define IMU_DRIVER_MESSAGE_EULERTOQUATERNIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_driver
{
template <class ContainerAllocator>
struct EulerToQuaternionRequest_
{
  typedef EulerToQuaternionRequest_<ContainerAllocator> Type;

  EulerToQuaternionRequest_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  EulerToQuaternionRequest_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EulerToQuaternionRequest_

typedef ::imu_driver::EulerToQuaternionRequest_<std::allocator<void> > EulerToQuaternionRequest;

typedef boost::shared_ptr< ::imu_driver::EulerToQuaternionRequest > EulerToQuaternionRequestPtr;
typedef boost::shared_ptr< ::imu_driver::EulerToQuaternionRequest const> EulerToQuaternionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator1> & lhs, const ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator1> & lhs, const ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eeec8b25a660789a89540dedcb2b06d6";
  }

  static const char* value(const ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeeec8b25a660789aULL;
  static const uint64_t static_value2 = 0x89540dedcb2b06d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_driver/EulerToQuaternionRequest";
  }

  static const char* value(const ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EulerToQuaternionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_driver::EulerToQuaternionRequest_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_DRIVER_MESSAGE_EULERTOQUATERNIONREQUEST_H
