// Generated by gencpp from file imu_driver/EulerToQuaternion.msg
// DO NOT EDIT!


#ifndef IMU_DRIVER_MESSAGE_EULERTOQUATERNION_H
#define IMU_DRIVER_MESSAGE_EULERTOQUATERNION_H

#include <ros/service_traits.h>


#include <imu_driver/EulerToQuaternionRequest.h>
#include <imu_driver/EulerToQuaternionResponse.h>


namespace imu_driver
{

struct EulerToQuaternion
{

typedef EulerToQuaternionRequest Request;
typedef EulerToQuaternionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EulerToQuaternion
} // namespace imu_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::imu_driver::EulerToQuaternion > {
  static const char* value()
  {
    return "b218cfe499191b24c074175e474522de";
  }

  static const char* value(const ::imu_driver::EulerToQuaternion&) { return value(); }
};

template<>
struct DataType< ::imu_driver::EulerToQuaternion > {
  static const char* value()
  {
    return "imu_driver/EulerToQuaternion";
  }

  static const char* value(const ::imu_driver::EulerToQuaternion&) { return value(); }
};


// service_traits::MD5Sum< ::imu_driver::EulerToQuaternionRequest> should match
// service_traits::MD5Sum< ::imu_driver::EulerToQuaternion >
template<>
struct MD5Sum< ::imu_driver::EulerToQuaternionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::imu_driver::EulerToQuaternion >::value();
  }
  static const char* value(const ::imu_driver::EulerToQuaternionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::imu_driver::EulerToQuaternionRequest> should match
// service_traits::DataType< ::imu_driver::EulerToQuaternion >
template<>
struct DataType< ::imu_driver::EulerToQuaternionRequest>
{
  static const char* value()
  {
    return DataType< ::imu_driver::EulerToQuaternion >::value();
  }
  static const char* value(const ::imu_driver::EulerToQuaternionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::imu_driver::EulerToQuaternionResponse> should match
// service_traits::MD5Sum< ::imu_driver::EulerToQuaternion >
template<>
struct MD5Sum< ::imu_driver::EulerToQuaternionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::imu_driver::EulerToQuaternion >::value();
  }
  static const char* value(const ::imu_driver::EulerToQuaternionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::imu_driver::EulerToQuaternionResponse> should match
// service_traits::DataType< ::imu_driver::EulerToQuaternion >
template<>
struct DataType< ::imu_driver::EulerToQuaternionResponse>
{
  static const char* value()
  {
    return DataType< ::imu_driver::EulerToQuaternion >::value();
  }
  static const char* value(const ::imu_driver::EulerToQuaternionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMU_DRIVER_MESSAGE_EULERTOQUATERNION_H
