# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from imu_driver/imu_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import sensor_msgs.msg
import std_msgs.msg

class imu_msg(genpy.Message):
  _md5sum = "adf4a68813b79eebfd5a91db0f9b4d2c"
  _type = "imu_driver/imu_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header Header
sensor_msgs/Imu IMU
sensor_msgs/MagneticField MagField
string raw

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: sensor_msgs/Imu
# This is a message to hold data from an IMU (Inertial Measurement Unit)
#
# Accelerations should be in m/s^2 (not in g's), and rotational velocity should be in rad/sec
#
# If the covariance of the measurement is known, it should be filled in (if all you know is the 
# variance of each measurement, e.g. from the datasheet, just put those along the diagonal)
# A covariance matrix of all zeros will be interpreted as "covariance unknown", and to use the
# data a covariance will have to be assumed or gotten from some other source
#
# If you have no estimate for one of the data elements (e.g. your IMU doesn't produce an orientation 
# estimate), please set element 0 of the associated covariance matrix to -1
# If you are interpreting this message, please check for a value of -1 in the first element of each 
# covariance matrix, and disregard the associated estimate.

Header header

geometry_msgs/Quaternion orientation
float64[9] orientation_covariance # Row major about x, y, z axes

geometry_msgs/Vector3 angular_velocity
float64[9] angular_velocity_covariance # Row major about x, y, z axes

geometry_msgs/Vector3 linear_acceleration
float64[9] linear_acceleration_covariance # Row major x, y z 

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: sensor_msgs/MagneticField
 # Measurement of the Magnetic Field vector at a specific location.

 # If the covariance of the measurement is known, it should be filled in
 # (if all you know is the variance of each measurement, e.g. from the datasheet,
 #just put those along the diagonal)
 # A covariance matrix of all zeros will be interpreted as "covariance unknown",
 # and to use the data a covariance will have to be assumed or gotten from some
 # other source


 Header header                        # timestamp is the time the
                                      # field was measured
                                      # frame_id is the location and orientation
                                      # of the field measurement

 geometry_msgs/Vector3 magnetic_field # x, y, and z components of the
                                      # field vector in Tesla
                                      # If your sensor does not output 3 axes,
                                      # put NaNs in the components not reported.

 float64[9] magnetic_field_covariance # Row major about x, y, z axes
                                      # 0 is interpreted as variance unknown"""
  __slots__ = ['Header','IMU','MagField','raw']
  _slot_types = ['std_msgs/Header','sensor_msgs/Imu','sensor_msgs/MagneticField','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Header,IMU,MagField,raw

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(imu_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Header is None:
        self.Header = std_msgs.msg.Header()
      if self.IMU is None:
        self.IMU = sensor_msgs.msg.Imu()
      if self.MagField is None:
        self.MagField = sensor_msgs.msg.MagneticField()
      if self.raw is None:
        self.raw = ''
    else:
      self.Header = std_msgs.msg.Header()
      self.IMU = sensor_msgs.msg.Imu()
      self.MagField = sensor_msgs.msg.MagneticField()
      self.raw = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.Header.seq, _x.Header.stamp.secs, _x.Header.stamp.nsecs))
      _x = self.Header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.IMU.header.seq, _x.IMU.header.stamp.secs, _x.IMU.header.stamp.nsecs))
      _x = self.IMU.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4d().pack(_x.IMU.orientation.x, _x.IMU.orientation.y, _x.IMU.orientation.z, _x.IMU.orientation.w))
      buff.write(_get_struct_9d().pack(*self.IMU.orientation_covariance))
      _x = self
      buff.write(_get_struct_3d().pack(_x.IMU.angular_velocity.x, _x.IMU.angular_velocity.y, _x.IMU.angular_velocity.z))
      buff.write(_get_struct_9d().pack(*self.IMU.angular_velocity_covariance))
      _x = self
      buff.write(_get_struct_3d().pack(_x.IMU.linear_acceleration.x, _x.IMU.linear_acceleration.y, _x.IMU.linear_acceleration.z))
      buff.write(_get_struct_9d().pack(*self.IMU.linear_acceleration_covariance))
      _x = self
      buff.write(_get_struct_3I().pack(_x.MagField.header.seq, _x.MagField.header.stamp.secs, _x.MagField.header.stamp.nsecs))
      _x = self.MagField.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.MagField.magnetic_field.x, _x.MagField.magnetic_field.y, _x.MagField.magnetic_field.z))
      buff.write(_get_struct_9d().pack(*self.MagField.magnetic_field_covariance))
      _x = self.raw
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Header is None:
        self.Header = std_msgs.msg.Header()
      if self.IMU is None:
        self.IMU = sensor_msgs.msg.Imu()
      if self.MagField is None:
        self.MagField = sensor_msgs.msg.MagneticField()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.Header.seq, _x.Header.stamp.secs, _x.Header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.IMU.header.seq, _x.IMU.header.stamp.secs, _x.IMU.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.IMU.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.IMU.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.IMU.orientation.x, _x.IMU.orientation.y, _x.IMU.orientation.z, _x.IMU.orientation.w,) = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 72
      self.IMU.orientation_covariance = _get_struct_9d().unpack(str[start:end])
      _x = self
      start = end
      end += 24
      (_x.IMU.angular_velocity.x, _x.IMU.angular_velocity.y, _x.IMU.angular_velocity.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 72
      self.IMU.angular_velocity_covariance = _get_struct_9d().unpack(str[start:end])
      _x = self
      start = end
      end += 24
      (_x.IMU.linear_acceleration.x, _x.IMU.linear_acceleration.y, _x.IMU.linear_acceleration.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 72
      self.IMU.linear_acceleration_covariance = _get_struct_9d().unpack(str[start:end])
      _x = self
      start = end
      end += 12
      (_x.MagField.header.seq, _x.MagField.header.stamp.secs, _x.MagField.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.MagField.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.MagField.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.MagField.magnetic_field.x, _x.MagField.magnetic_field.y, _x.MagField.magnetic_field.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 72
      self.MagField.magnetic_field_covariance = _get_struct_9d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.raw = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.raw = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.Header.seq, _x.Header.stamp.secs, _x.Header.stamp.nsecs))
      _x = self.Header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.IMU.header.seq, _x.IMU.header.stamp.secs, _x.IMU.header.stamp.nsecs))
      _x = self.IMU.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4d().pack(_x.IMU.orientation.x, _x.IMU.orientation.y, _x.IMU.orientation.z, _x.IMU.orientation.w))
      buff.write(self.IMU.orientation_covariance.tostring())
      _x = self
      buff.write(_get_struct_3d().pack(_x.IMU.angular_velocity.x, _x.IMU.angular_velocity.y, _x.IMU.angular_velocity.z))
      buff.write(self.IMU.angular_velocity_covariance.tostring())
      _x = self
      buff.write(_get_struct_3d().pack(_x.IMU.linear_acceleration.x, _x.IMU.linear_acceleration.y, _x.IMU.linear_acceleration.z))
      buff.write(self.IMU.linear_acceleration_covariance.tostring())
      _x = self
      buff.write(_get_struct_3I().pack(_x.MagField.header.seq, _x.MagField.header.stamp.secs, _x.MagField.header.stamp.nsecs))
      _x = self.MagField.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.MagField.magnetic_field.x, _x.MagField.magnetic_field.y, _x.MagField.magnetic_field.z))
      buff.write(self.MagField.magnetic_field_covariance.tostring())
      _x = self.raw
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Header is None:
        self.Header = std_msgs.msg.Header()
      if self.IMU is None:
        self.IMU = sensor_msgs.msg.Imu()
      if self.MagField is None:
        self.MagField = sensor_msgs.msg.MagneticField()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.Header.seq, _x.Header.stamp.secs, _x.Header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.IMU.header.seq, _x.IMU.header.stamp.secs, _x.IMU.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.IMU.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.IMU.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.IMU.orientation.x, _x.IMU.orientation.y, _x.IMU.orientation.z, _x.IMU.orientation.w,) = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 72
      self.IMU.orientation_covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      _x = self
      start = end
      end += 24
      (_x.IMU.angular_velocity.x, _x.IMU.angular_velocity.y, _x.IMU.angular_velocity.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 72
      self.IMU.angular_velocity_covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      _x = self
      start = end
      end += 24
      (_x.IMU.linear_acceleration.x, _x.IMU.linear_acceleration.y, _x.IMU.linear_acceleration.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 72
      self.IMU.linear_acceleration_covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      _x = self
      start = end
      end += 12
      (_x.MagField.header.seq, _x.MagField.header.stamp.secs, _x.MagField.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.MagField.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.MagField.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.MagField.magnetic_field.x, _x.MagField.magnetic_field.y, _x.MagField.magnetic_field.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 72
      self.MagField.magnetic_field_covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.raw = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.raw = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
